### ISSUE TITLE
Error editing the selected option from dropdown

### ISSUE THREAD

**Issue by maguilera-esricanada** [zhif7782/0525-holistic-testing#18]
**Describe the bug**
When I selected an option from the drop down list, I am able to edit the selected value, and after that the dropdown stays gray (disabled)

**To Reproduce**
1. Go to 'the drop down question'
2. Click on 'select one option'
3. Edit the selected option, add more characters
4. The question will become gray or disabled

**Expected behavior**
don't allow to edit a selected option from the dropdown list

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Capture](https://github.com/zhif7782/0525-holistic-testing/assets/134634596/0df95032-c97a-4974-914c-b151dea15d19)

**Comment by oopsliu** [comment]
@maguilera-esricanada Thanks for raising it; this is an expected behavior with the autocomplete appearance of the dropdown question: entering text in the field limits the drop-down menu to only answers that contain that text. When you add some text to a  selected option, the dropdown fails to find a match, so it greyed out.
